services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - path: ./.env.local
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: .
          target: /site
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
