allowBuilds:
  '@parcel/watcher': false
  '@sentry/cli': false
  esbuild: false
  msgpackr-extract: false
  sharp: false
  unrs-resolver: false
overrides:
  ws: ^8.21.0
minimumReleaseAge: 10080 # minutes = 7 days
