version: '3.8'
services:
  check-nginx-conf:
    image: owasp/modsecurity-crs:4.25.1-nginx-lts
    user: root
    ports:
      - "80:80"
    environment:
      - PORT=${PORT:-80}
    command:
      - '/data/test-erb-nginx-conf.sh'
    volumes:
      - ./test-erb-nginx-conf.sh:/data/test-erb-nginx-conf.sh
      - ./servers.conf.erb:/data/servers.conf.erb
      - ./waf_rules.conf:/app/waf_rules.conf