name: Lint

on:
  pull_request:
    branches: [ main ]
    

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint
        working-directory: ./site
        run: npm run lint
