name: Test nginx redirections config

on:
  pull_request:
    branches: [ main ]
    

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: prepare before build
        run: |
           sudo apt-get install -qy make curl
           uname -a

      # - name: Build & test staging
      #   run: |
      #      set -e
      #      ./proxy-staging/.ci/build-and-test.sh
      
      - name: Build & test prod
        run: |
           cd ./proxy-prod/.ci/
           docker-compose run --rm check-nginx-conf
