name: Test nginx redirections config

on:
  pull_request:
    branches: [ main ]
    

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: prepare before build
        run: |
           sudo apt-get install -qy make curl
           uname -a

      - name: Build & test
        run: |
           set -e
           make -C ./redirections/.ci test
