name: Nginx config test

on:
  pull_request:
    branches: [ main ]
    

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check Docker version
        run: docker --version
      - name: Check Docker Compose version
        run: docker-compose --version
      # - name: Build & test staging
      #   run: docker-compose run  --rm check-nginx-conf"
      - name: Build & test prod
        run: | 
          cd .ci
          docker-compose run  --rm check-nginx-conf
